version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y wget sudo
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack
      - run: stack --version
      - run: stack setup
      - run: stack test
  test:
    docker:
      - image: haskell:8.2.1
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
